### ISSUE TITLE
npm install -> 404 Not Found

### ISSUE THREAD

**Issue by domwoe** [auth0/angular-auth0-auth#1]
I tried to install the package with npm but it seems not to be available 

`npm ERR! 404 Not Found: angular-auth0-auth@latest`

**Comment by domwoe** [comment]
Installed it using the work around to install directly from GitHub
`npm install git+https://git@github.com/auth0/angular-auth0-auth`

**Comment by domwoe** [comment]
I'm still having issues. I installed the module and it appears in `package.json` as well as in the `node_modules` folder. However, Angular is not able to resolve the module:

`ERROR in src/app/app.module.ts(19,41): error TS2307: Cannot find module 'angular-auth0-auth'.`

**Comment by AdrianSima** [comment]
It seems that npm installs an empty package. If you go to node_modules/angular-auth0-auth/ you will see that there is actually no usable code files, only the config json files.

Probably the package is not yet ready?
Maybe @kmaida can give us some insight on the status of this package. I would really want to start using this in my **Angular 5** web apps.

**Comment by kmaida** [comment]
@domwoe @AdrianSima Correct, the package is not ready yet. It has not been published to npm, which is why you receive errors as @AdrianSima has mentioned.

The package can actually be downloaded and installed from the GitHub repo by saving manually to the node_modules folder and running npm install; this will work, but is not recommended at this time. The reason that this package has not been published yet is:

- the package is going to be renamed and moved to `@auth0/{something, presumably angular-sdk}`
- the underlying library that the package depends on, auth0.js, is going to be swapped out for a newer and more SPA-specific library in the near future; work on this project has temporarily been suspended to wait for the release of the new library in order to prevent large breaking changes, as the functionality of the package and its docs will need to be fully revised

If you're looking to implement Auth0 with Angular right now, we have several tutorials with details on how to do so. The simplest way to get up and running quickly would be to follow the instructions here: https://github.com/auth0/blog/blob/master/_includes/asides/angular.markdown

We are currently working on updating existing Angular content to adhere to newer strategies and the READMEs for this library are up to date. However, the library is not officially published yet. It should be fairly simple to take the authentication service file from this library and use it in an application normally, however.

If you have any questions or concerns, I'd be happy to chat further.

**Comment by AdrianSima** [comment]
@kmaida Thank you very much for the quick reply. I was thinking that this might be the situation. 

The info you provided is extremely helpful for setting up a service for now. I can't wait to see the changes you will bring to `auth0-js` replacement.

**Comment by lucasklaassen** [comment]
@kmaida the practices in this repo are strong and I like where you guys are taking it. What's the best way to stay updated on the progress of this build for the future? Any updated ETA?

**Comment by dchahla** [comment]
@kmaida
ded link.
https://github.com/auth0/blog/blob/master/_includes/asides/angular.markdown

**Comment by kmaida** [comment]
This repo is being closed, as newer guidance is being created and SDKs for JS frameworks should not be used.
